data=[[("I've been romantic and imaginative","e"),("I've been pragmatic and down to earth","b")],
[("I have tended to take on confrontations","g"),("I have tended to avoid confrontations","a")],
[("I have typically been diplomatic,charming, and ambitious","c"),("I have typically been direct, formal, and idealistic","d")],
[("I have tended to be focused and intense  ","h"),("I have tended to be spontaneous and fun-loving ","i")],
[("I have been a hospitable person and have enjoyed welcoming new friends into my life","f"),("I have been a private person and have not mixed much with others       ","e")],
[("It's been difficult for me to relax and stop worrying about potential problems","b"),("It's been difficult for me to get myself worked up about potential problems","a")],
[("I've been more of a 'street-smart' survivor","g"),("I've been more of a 'high-minded' idealist","d")],
[("I have needed to show affection to people","f"),("I have preferred to maintain some distance with people","h")],
[("When presented with a new experience, I've usually asked myself it it would be useful to me ","c"),("When presented with a new experience, I've usually asked myself it it would be enjoyable ","i")],
[("I have tended to focus too much on myself  ","e"),("I have tended to focus too much on others  ","a")],
[("Others have depended on my insight and knowledge","h"),("Others have depended on my strength and decisiveness","g")],
[("I have come across as being too unsure of myself","b"),("I have come across as being too sure of myself ","d")],
[("I have been more relationship-oriented than goal-oriented","f"),("I have been more goal-oriented than relationship-oriented","c")],
[("I have not been able to speak up for myself very well","e"),("I have not been outspoken- I've said what others wished they had the nerve to say","i")],
[("It's been difficult for me to stop considering alternatives and do something definite  ","h"),("It's been difficult for me to take it easy and be more flexible","d")],
[("I have tended to be careful and hesitant   ","b"),("I have tended to be bold and domineering   ","g")],
[("My reluctance to get too involved has gotten me into trouble with people","a"),("My eagerness to have people depend on me has gotten me into trouble with them    ","f")],
[("Usually, I have been able to put mu feelings aside to get the job done","c"),("Usually, I have needed to work through my feelings before I could act","e")],
[("Generally, I've been methodical and cautious   ","b"),("Generally, I've been adventurous and taken risks   ","i")],
[("I have tended to be a supportive, giving person who seeks intimacy with others   ","f"),("I have tended to be a serious, reserved person who likes discussing issues","d")],
[("I've often felt the need to be a 'pillar of strength'","g"),("I've often felt the need to perform perfectly","c")],
[("I've typically been interested in asking tough questions and maintaining my independence    ","h"),("I've typically been interested in maintaining my stability and peace of mind       ","a")],
[("I've been a bit cynical and skeptical","b"),("I've been a bit mushy and sentimental","f")],
[("I've often worried that I'm missing out on something better.","i"),("I've often worried that if I let down my guard, someone will take advantage of me","g")],
[("My habit of being 'stand-offish' has annoyed people...   ","e"),("My habit of telling people what to do has annoyed people     ","d")],
[("I have tended to get anxious if there was too much excitement and stimulation","a"),("I have tended to get anxious if there wasn't enough excitement and stimulation","i")],
[("I have depended on my friends and they have known that they can depend on me.","b"),("I have not depended on people; I have done things on my own","c")],
[("I have tended to be detached and preoccupied  ","h"),("I have tended to be moody and self-absorbed  ","e")],
[("I have liked to challenge people and 'shake them up'","g"),("I have liked to comfort people and calm them down    ","f")],
[("I have generally been an outgoing, sociable person","i"),("I have generally been an earnest, self-disciplined person","d")],
[("l've wanted to 'fit in' with others—I get uncomfortable when I stand out too much","a"),("I've wanted to stand out from others--I get uncomfortable when I don't distinguish myself","c")],
[("Pursuing my personal interests has been more important to me than having stability and security.","h"),("Having stability and security has been more important to me than pursuing my personal interests.  ","b")],
[("When I've had conflicts with others, I've tended to withdraw ","e"),("When I've had conflicts with others, I've rarely backed down","g")],
[("I have given in too easily and let others push me around.","a"),("I have been too uncompromising and demanding with others","d")],
[("I've been appreciated for my unsinkable spirit and resourcefulness","i"),("I've been appreciated for my deep caring and personal warmth","f")],
[("I have wanted to make a favorable impression on others","c"),("I have cared little about making a favorable impression on others.","h")],
[("I've depended on my perseverance and common sense","b"),("I've depended on my imagination and moments of inspiration.","e")],
[("Basically, I have been easy-going and agreeable.","a"),("Basically, I have been hard-driving and assertive","g")],
[("I have worked hard to be accepted and well-liked","c"),("Being accepted and well-liked has not been a high priority for me","d")],
[("In reaction to pressure from others. I have become more withdrawn","h"),("In reaction to pressure from others, I have become more assertive","i")],
[("People have been interested in me because I've been outgoing, engaging, and interested in them.","f"),("People have been interested in me because I've been quiet, unusual, and deep","e")],
[("Duty and responsibility have been important values for me.    ","b"),("Harmony and acceptance have been important values for me   ","a")],
[("I've tried to motivate people by making big plans and big promises.","g"),("I've tried to motivate people by pointing out the consequences of not following my advice","d")],
[("I have seldom been emotionally demonstrative  ","h"),("I have often been emotionally demonstrative","f")],
[("Dealing with details has not been one of my strong suits.","i"),("I have excelled at dealing with details  ","c")],
[("I have often emphasized how different I am from most peoples, especially my family.","e"),("I have often emphasized how much I have in common with most people, especially my family.","a")],
[("When situations have gotten heated, I have tended to stay on the sidelines.  ","h"),("When situations have gotten heated, I have tended to get right into the middle of things","g")],
[("I have stood by my friends, even when they have been wrong ","b"),("I have not wanted to compromise what is right even for friendship","d")],
[("I've been a well-meaning supporter","f"),("I've been a highly-motivated go-getter","c")],
[("When troubled, I have tended to brood about my problems.","e"),("When troubled, I have tended to find distractions for myself.","i")],
[("Generally, I've had strong convictions and a sense of how things should be.","d"),("Generally, I've had serious doubts and have questioned how things seemed to be","h")],
[("I've created problems with others by being pessimistic and complaining  ","b"),("I've created problems with others by being bossy and controlling    ","g")],
[("I have tended to act on my feelings and let the 'chips fall where they may'","f"),("I have tended not to act on my feelings lest they stir up more problems  ","a")],
[("Being the center of attention has usually felt natural to me.  ","c"),("Being the center of attention has usually felt strange to me  ","e")],
[("I've been careful, and have tried to prepare for unforeseen problems.","b"),("I've been spontaneous, and have preferred to improvise as problems come up","i")],
[("I have gotten angry when others have not shown enough appreciation for what I have done for them.","f"),("I have gotten angry when others have not listened to what I have told them  ","d")],
[("Being independent and self-reliant has been important to me","g"),("Being valued and admired has been important to me  ","c")],
[("When I've debated with friends, I've tended to press my arguments forcefully","h"),("When I've debated with friends, I've tended to let things go to prevent hard feelings","a")],
[("I have often been possessive of loved ones--I have had trouble letting them be","f"),("I have often 'tested' loved ones to see if they were really there for me   ","b")],
[("Organizing resources and making things happen has been one of my major strengths","g"),("Coming up with new ideas and getting people excited about them has been one of my major strengths.","i")],
[("I've tended to be driven and very hard on myself  ","d"),("I've tended to be too emotional and rather undisciplined  ","e")],
[("I have tried to keep my life fast-paced, intense, and exciting.","i"),("I have tried to keep my life regular, stable, and peaceful","a")],
[("Even though I've had successes, I've tended to doubt my abilities.","b"),("Even though I've had setbacks, I've had a lot of confidence in my abilities","c")],
[("I generally have tended to dwell on my feelings and to hold onto them for a long time","e"),("I generally have tended to minimize my feelings and not pay very much attention to them","h")],
[("I have provided many people with attention and nurturance. ","f"),("I have provided many people with direction and motivation ","g")],
[("I've been a bit serious and strict with myself. ","d"),("I've been a bit free-wheeling and permissive with myself. ","i")],
[("I've been self-assertive and driven to excel  ","c"),("I've been modest and have been happy to go at my own pace","a")],
[("I have been proud of my clarity and objectivity  ","h"),("I have been proud of my reliability and commitment   ","b")],
[("I have spent a lot of time looking inward-understanding my feelings has been important to me.","e"),("I have not spent much time looking inward getting things done has been important to me.  ","g")],
[("Generally, I have thought of myself as a sunny, casual person.  ","a"),("Generally, I have thought of myself as a serious, dignified person. ","d")],
[("I've had an agile mind and boundless energy.  ","i"),("I've had a caring heart and deep dedication  ","f")],
[("I have pursued activities that had a substantial potential for reward and personal recognition.","c"),("I have been willing to give up reward and personal recognition fi it meant doing work I was really interested ni","h")],
[("Fulfilling social obligations has seldom been high on my agenda. ","e"),("I have usually have taken my social obligations very seriously     ","b")],
[("In most situations, I have preferred to take the lead     ","g"),("In most situations, I have preferred to let someone else take the lead","a")],
[("Over the years, my values and lifestyle have changed several times.","c"),("Over the years, my values and lifestyle have remained fairly consistent.","d")],
[("Typically, I have not had much self-discipline.    ","i"),("Typically, I have not had much connection with people. ","h")],
[("I have tended to withhold my affection, and have wanted others to come into my world.","e"),("I have tended to give my affection too freely, and have wanted to extend myself to others.","f")],
[("I have had a tendency to think of worst case scenarios     ","b"),("I have had a tendency to think that everything will work out for the best","a")],
[("People have trusted me because I am confident and can look out for them","g"),("People have trusted me because I am fair and will do what is right ","d")],
[("Often, I have been so involved in my own projects that I have become isolated from others.","h"),("Often, I have been so involved with others that I have neglected my own projects. ","f")],
[("When meeting someone new, I have usually been poised and self-contained.  ","c"),("When meeting someone new, I have usually been chatty and entertaining  ","i")],
[("Generally speaking, I have tended to be pessimistic.  ","e"),("Generally speaking, I have tended to be optimistic  ","a")],
[("I have preferred to inhabit my own little world.  ","h"),("I have preferred to let the world know I'm here.  ","g")],
[("I have often been troubled by nervousness, insecurity, and doubt  ","b"),("I have often been troubled by anger, perfectionism, and impatience.  ","d")],
[("I realize that I have often been too personal and intimate  ","f"),("I realize that I have often been too cool and aloof   ","c")],
[("I have lost out because I have not felt up to taking opportunities.","e"),("I have lost out because I have pursued too many possibilities","i")],
[("I have tended to take along time to getting into action","h"),("I have tended to get into action quickly.    ","d")],
[("I usually have had difficulty making decisions","b"),("I seldom have had difficulty making decisions.","g")],
[("I have had a tendency to come on a little too strong with people.","f"),("I have had a tendency not to assert myself enough with people.","a")],
[("Typically, I have been even-tempered.  ","c"),("Typically, I have had strong changes of mood","e")],
[("When I've been unsure of what to do, I've often sought the advice of others.","b"),("When I've been unsure of what to do, I've tried different things to see what worked best for me.","i")],
[("I have worried that I would be left out of other's activities.  ","f"),("I have worried that others' activities would distract me from what I had to do","d")],
[("Typically, when I have gotten angry, I have told people off   ","g"),("Typically, when I have gotten angry, I have become distant    ","c")],
[("I've tended to have trouble falling asleep","h"),("I've tended to fall asleep easily.     ","a")],
[("I have often tried to figure out how I could get closer to others","f"),("I have often tried to figure out what others want from me   ","b")],
[("I have usually been measured, straight-talking, and deliberate.","g"),("I have usually been excitable, fast-talking, and witty.","i")],
[("Often, I have not spoken up when I've seen others making a mistake.","e"),("Often, I have helped others see that they are making a mistake","d")],
[("During most of my life, I have been a stormy person who has had many volatile feelings","i"),("During most of my life, I have been a steady person in whom 'still waters run deep","a")],
[("When I have disliked people, I have usually tried hard to stay cordial despite my feelings.","c"),("When I have disliked people, I have usually let them know it—one way or another   ","b")],
[("Much of my difficulty with people has come from my touchiness and taking everything to personally","e"),("Much of my difficulty with people has come from my not caring about social conventions ","h")],
[("My approach has been to jump in and rescue people.      ","f"),("My approach has been to show people how to help themselves    ","g")],
[("Generally, I have enjoyed 'letting go' and pushing the limits","i"),("Generally, I have not enjoyed losing control of myself very much","d")],
[("I've been overly concerned with doing better than others","c"),("I've been overly concerned with making things okay for others.","a")],
[("My thoughts generally have been speculative-involving my imagination and curiosity.","h"),("My thoughts generally have been practical-just trying to keep things going    ","b")],
[("One of my main assets has been my ability to take charge of situations.  ","g"),("One of my main assets has been my ability to describe internal states      ","e")],
[("I have pushed to get things done correctly, even if it made people uncomfortable.","d"),("I have not liked feeling pressured, so I have not liked pressuring anyone else","a")],
[("I've often taken pride in how important I am in others' lives ","f"),("I've often taken pride in my gusto and openness to new experiences ","i")],
[("I have perceived that I've often come across to others as presentable, even admirable.","c"),("I have perceived that I've often come across to others as unusual, even odd ","h")],
[("I have mostly done what I had to do.    ","b"),("I have mostly done what I wanted to do     ","e")],
[("I have usually enjoyed high-pressure, even difficult, situations","g"),("I have usually disliked being in high-pressure, even difficult, situations","a")],
[("I've been proud of my ability to be flexible what's appropriate or important often changes.","c"),("I've been proud of my ability to take a stand—I've been firm about what I believe in  ","d")],
[("My style has leaned toward spareness and austerity.     ","h"),("My style has leaned toward excess and over-doing things     ","i")],
[("My own health and well-being have suffered because of my strong desire to help others.","f"),("My relationships have suffered because of my strong desire to attend to my personal needs","e")],
[("Generally speaking, I've been too open and naive.   ","a"),("Generally speaking, I've been too wary and guarded   ","b")],
[("I have sometimes put people of by being too aggressive ","g"),("I have sometimes put people of by being too 'up-tight'   ","d")],
[("Being of service and attending to the needs of others has been a high priority for me","f"),("Finding alternative ways of seeing and doing things has been a high priority for me    ","h")],
[("I've been single-minded and persistent in pursuing my goals    ","c"),("I've preferred to explore various courses of action to see where they lead","i")],
[("I have frequently been drawn to situations that stir up deep, intense emotions.","e"),("I have frequently been drawn to situations that make me feel calm and at ease","a")],
[("I have cared less about practical results than about pursuing my interests","h"),("I have been practical and have expected my work to have concrete results","g")],
[("I have had a deep need to belong  ","b"),("I have had a deep need to feel balanced","d")],
[("In the past, I've probably insisted on too much closeness in my friendships.","f"),("In the past, I've probably kept too much distance in my friendships. ","c")],
[("I've had a tendency to keep thinking about things from the past.","e"),("I've had a tendency to keep anticipating things I'm going to do","i")],
[("I've tended to see people as intrusive and demanding.   ","h"),("I've tended to see people as disorganized and irresponsible. ","d")],
[("Generally, I have not had much confidence in myself     ","b"),("Generally, I have had confidence only in myself. ","g")],
[("Eve probably been too passive and uninvolved.","a"),("I've probably been too controlling and manipulative","f")],
[("I've frequently been stopped in my tracks by my self-doubt.","e"),("I've rarely let self-doubt stand in my way    c      ")],
[("Given a choice between something familiar and something new, I've usually chosen something new","i"),("I've generally chosen what I knew I already liked: why be disappointed with something I might not like?","b")],
[("I have given a lot of physical contact to reassure others about how I feel about them.    ","f"),("I have generally felt that real love does not depend on physical contact ","d")],
[("When I've needed to confront someone, I've often been too harsh and direct","g"),("When I've needed to confront someone, I've often 'beaten around the bush' too much","c")],
[("I have been attracted to subjects that others would probably find disturbing, even frightening","h"),("I have preferred not to spend my time dwelling on disturbing, frightening subjects ","a")],
[("I have gotten into trouble with people by being too intrusive and interfering.  ","f"),("I have gotten into trouble with people by being too evasive and uncommunicative.   ","b")],
[("I've worried that I don't have the resources to fulfill the responsibilities I've taken on","g"),("I've worried that I don't have the self-discipline to focus on what will really fulfill me.  ","i")],
[("Generally, I've been a highly intuitive, individualistic person ","e"),("Generally, I've been a highly organized, responsible person  ","d")],
[("Overcoming inertia has been one of my main problems  ","a"),("Being unable to slow down has been one of my main problems","i")],
[("When I've felt insecure, I've reacted by becoming arrogant and dismissive.","c"),("When I've felt insecure, I've reacted by becoming defensive and argumentative","b")],
[("I have generally been open-minded and willing to try new approaches.","h"),("I have generally been self-revealing and wiling to share my feelings with others.","e")],
[("I've presented myself to others as tougher than I really am. ","g"),("I've presented myself to others as caring more than I really do ","f")],
[("I usually have followed my conscience and reason   ","d"),("I usually have followed my feelings and impulses   ","i")],
[("Serious adversity has made me feel hardened and resolute.","c"),("Serious adversity has made me feel discouraged and resigned","a")],
[("I usually have made sure that I had some kind of 'safety net' to fall back on.","b"),("I usually have chosen to live on the edge and to depend on as little as possible.","h")],
[("I've had to be strong for others, so I haven't had time to deal with my feelings and fears.","g"),("I've had difficulty coping with my feelings and fears, so it's been hard for me to be strong for others.","e")],
[("I have often wondered why people focus on the negative when there is so much that's wonderful about life.","a"),("I have often wondered why people are so happy when so much in life is messed up.  ","d")],
[("I have tried hard not to be seen as a selfish person. ","f"),("I have tried hard not to be seen as a boring person   ","i")],
[("I have avoided intimacy when I feared I would be overwhelmed by people's needs and demands.","h"),("I have avoided intimacy when I feared I would not be able to live up to people's expectations of me.","c")]]